//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieActor_Map
    {
        public long Id { get; set; }
        public long MovieId { get; set; }
        public long ActorId { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
